@startuml

Server -> EkgService : HTTP get
EkgService -> EkgController : getEkgSessions()
EkgController ->> ekgDB : getAllSession()

Server -> EkgService : HTTP get
EkgService -> EkgController : getEkgData()
EkgController ->> ekgDB : getData()

entity      SQLDatabase      as sqldb
ekgDB -> sqldb  : getSessions()
ekgDB <<-- sqldb : Return
EkgController <-- ekgDB : Return ekgSessionList
EkgService <<-- EkgController : Return
Server <<-- EkgService : Return

ekgDB -> sqldb  : getMeasurementFromSession()
ekgDB <<-- sqldb : Return
EkgController <-- ekgDB : Return ekgMeasurements
EkgService <<-- EkgController : Return
Server <<-- EkgService : Return

@enduml